---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/pokemons":
    get:
      summary: Retrieves a list of pokemons
      tags:
      - Pokemons
      responses:
        '200':
          description: pokemons found
    post:
      summary: Creates a pokemon
      tags:
      - Pokemons
      parameters: []
      responses:
        '201':
          description: pokemon created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                order:
                  type: integer
                base_experience:
                  type: integer
                height:
                  type: integer
                weight:
                  type: integer
                types:
                  type: array
                  items:
                    type: string
              required:
              - name
              - order
              - base_experience
              - height
              - weight
  "/api/v1/pokemons/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
    get:
      summary: Retrieves a pokemon
      tags:
      - Pokemons
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: pokemon found
        '404':
          description: Pokemon not found
    put:
      summary: Updates a pokemon
      tags:
      - Pokemons
      parameters: []
      responses:
        '200':
          description: pokemon updated
        '404':
          description: Pokemon not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                order:
                  type: integer
                base_experience:
                  type: integer
                height:
                  type: integer
                weight:
                  type: integer
                types:
                  type: array
                  items:
                    type: string
              required:
              - name
              - order
              - base_experience
              - height
              - weight
    delete:
      summary: Deletes a pokemon
      tags:
      - Pokemons
      responses:
        '200':
          description: pokemon deleted
        '404':
          description: Pokemon not found
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: www.example.com
